FROM alpine:latest

RUN apk add --no-cache \
    bash \
    iproute2 \
    iptables \
    tcpdump \
    wireguard-tools \
    strongswan \
    python3 \
    py3-pip \
    netcat-openbsd \
    curl
    
WORKDIR /app

COPY filial1/scripts/ /app/scripts/

# Копирование конфигурационных файлов VPN
COPY filial1/wg0.conf /etc/wireguard/wg0.conf

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /app/scripts/*.py

ENTRYPOINT ["/entrypoint.sh"]
